config:
  target: "https://pp.trunarrative.cloud"
  http:
    timeout: 60
  plugins:
    fake-data:
      randAmount:
        min: 250000
        max: 1000000
      randNumber:
        min: 1
        max: 9
  phases:
    - duration: 12
      arrivalRate: 3
      rampTo: 4
      name: Spike phase
  defaults:
    headers:
      Content-Type: "application/json"
      Authorization: "Basic AUTHORIZATION_CODE"
  payload:
    - path: "../../data/hapic.csv"
      fields:
        - currencyCode
        - thirdPartyID
  variables:
    # Common vars
    transaction_type: ["CREDIT", "DEBIT"]
    risk_level: ["1", "2", "3", "4", "5"]
    payment_type: ["TARGET", "SEPA", "MT103", "SEPA-INSTANT"]
    country_of_transaction: ["USA", "IND", "GBR", "BRA", "JAP"]
    party_type: ["IR", "IN", "CR", "CN"]
    external_rule_outcome_keyword: ["guns", "alcohol", "golfing", "skydiving"]
    counter_party_risk: ["HIGHRISK", "ODDRISK", "INVERTEDRISK", "TRIPLERISK"]
    person_risk: ["HIGHRISK", "TEENYRISK", "PINKRISK", "PROPERRISK"]
    # Project specif vars
    #Siauliu Bankas
    client: ["PPP_Client9", "  " ]
