config:
  target: "https://pp.trunarrative.cloud"
  plugins:
    fake-data: {}
  phases:
    - duration: 5
      arrivalRate: 1
      rampTo: 2
      name: Warm up phase
    - duration: 12
      arrivalRate: 3
      rampTo: 4
      name: Spike phase
  defaults:
    headers:
      Content-Type: "application/json"
      Authorization: "Basic AUTHORIZATION_CODE"
  payload:
    - path: "../../data/sample-data.csv"
      fields:
        - clientReference
        - accountReference
        - effectiveDateTime
  variables:
    # Common vars
    transaction_type: ["CREDIT", "DEBIT"]
    risk_level: ["1", "2", "3", "4", "5"]
    payment_type: ["TARGET", "SEPA", "MT103", "SEPA-INSTANT"]
    country_of_transaction: ["USA", "IND", "GBR", "BRA", "JAP"]
    party_type: ["IR", "IN", "CR", "CN"]
    # Project specif vars
