config:
  target: "https://pp.trunarrative.cloud"
  http:
    timeout: 60
  plugins:
    ensure: {}
    fake-data: {}
  defaults:
    headers:
      Content-Type: "application/json"
      Authorization: "Basic {{ $env.TOKEN }}"
  ensure:
    maxErrorRate: 0
    thresholds:
      - http.response_time.min: 1000
      - http.response_time.mean: 2000
      - http.response_time.p95: 2000
      - http.response_time.p99: 3000
      - http.response_time.max: 5000
