config:
  target: "https://pp.trunarrative.cloud"
  http:
    timeout: 60
  plugins:
    ensure: {}
    fake-data: {}
  defaults:
    headers:
      Content-Type: "application/json"
      Authorization: "Basic {{ $env.TOKEN }}"

