#!/usr/bin/env bash

set -euo pipefail

POST_FILE="loadtest1900.txt"
AUTH_BASIC="${AUTH_BASIC:-empty}"
SITE="${SITE:-pp}"
DIR="$(date +"%Y-%m-%d")"

if [[ $AUTH_BASIC == "empty" ]]; then
  printf "Env var AUTH_BASIC not set\n" >&1
  exit 1
fi

mkdir -p "$DIR"

for t in 5:10000 10:20000 15:30000 20:40000 25:50000 30:60000; do
  c=${t/:*/}
  n=${t/*:/}
  ab -p $POST_FILE -T application/json -H "Authorization: Basic ${AUTH_BASIC}" -c $c -n $n "https://${SITE}.trunarrative.cloud/TruAPI/rest/TruRest/RunJourney" 2>&1 | tee "${DIR}/c$(printf %02d $c)_n${n}.txt"
done

