name: Art Test - Siauliu Bankas Strategy
run-name: ${{ github.actor }} initiated a Artillery performance test
on:
  workflow_dispatch:
    inputs:
      duration:
        required: true
        type: string
        description: "Duration"
        default: "300"
      arrival_rate:
        required: true
        type: string
        description: "Arrival Rate"
        default: "1"
jobs:
  test-flow:
    uses: ./.github/workflows/artillery-template.yml
    with:
      environment: "pp"
      config_file_name: "Siauliu_Bankas"
      duration: ${{ inputs.duration }}
      arrival_rate: ${{ inputs.arrival_rate }}
