name: Run Python on PR

# Trigger the workflow when a pull request is opened, reopened, or synchronized (i.e., when commits are pushed to the PR) for the main branch.
on:
  pull_request:
    branches:
      - Whitehat

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # Defines the runner environment (Ubuntu in this case).

    steps:
      # Step 1: Check out the code from the repository.
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python (specify the Python version if needed).
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'  # Replace '3.x' with the specific version, e.g., '3.9'.

      # Step 3: Install dependencies (if your script requires any).
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # If you have a requirements file

      # Step 4: Run the Python script.
      - name: Run Python script
        env:
          RISK_TOKEN: ${{ secrets.RISK_TOKEN}}  # Secret reference
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # Another secret
        run: |
          python GithubRestOperations.py  # Replace with the path to your Python script
