name: Performance Test
run-name: "Performance Test: ${{ inputs.test_file }} Duration: ${{ inputs.duration }}s RPS: ${{ inputs.arrival_rate }}"

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: "Environment"
        options:
          - pp
      test_file:
        type: choice
        description: "Test file"
        options:
          - AeraPass.yml
          - Ardshin.yml
          - BaselineJourney.yml
          - BaselineStrategy.yml
          - HapicLtd.yml
          - Paytrix.yml
          - SiauliuBankas.yml
          - TradeStationAccountCreation.yml
          - TradeStationOngoingTransactions.yml
          - WhiteHat.yml
      duration:
        required: true
        type: string
        description: "Duration (seconds)"
        default: "300"
      arrival_rate:
        required: true
        type: string
        description: "Requests per second"
        default: "1"

jobs:
  test:
    uses: ./.github/workflows/template.yml
    with:
      env: ${{ inputs.env }}
      test_file: ${{ inputs.test_file }}
      duration: ${{ inputs.duration }}
      arrival_rate: ${{ inputs.arrival_rate }}
