name: Start Performance Runner EC2
on:
  workflow_call:
jobs:
  start-ec2:
    runs-on: [self-hosted, rn-runner]
    container: 225237029829.dkr.ecr.eu-west-2.amazonaws.com/trunarrative/alpine:infra
    steps:
      - uses: LexisNexis-RBA/rn-sre-cicd/assume_role@v1
      - name: Starting Performance Runner
        shell: bash
        run: | 
          source assume_role pp
          aws autoscaling update-auto-scaling-group --auto-scaling-group-name lon-mgmt-github-runner-performance --min-size 1 --desired-capacity 1
          echo "Starting the Performance Test Runner"
          source assume_role -u