name: Performance Test Template

on:
  workflow_call:
    inputs:
      env:
        type: string
      test_file:
        type: string
        required: true
      duration:
        type: string
        required: true
      arrival_rate:
        type: string
        required: true

env:
  CHANNEL: "performance-testing"
  PIPELINE: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

jobs:
  start-runner:
    uses: ./.github/workflows/start_runner.yml

  performance-test:
    needs: start-runner
    runs-on: [self-hosted, rn-performance]
    container: 225237029829.dkr.ecr.eu-west-2.amazonaws.com/trunarrative/alpine:infra
    steps:
      - uses: actions/checkout@v4
      - uses: LexisNexis-RBA/rn-sre-cicd/assume_role@main
      - uses: LexisNexis-RBA/rn-sre-cicd/ppslack@main
      - name: Execute
        shell: bash
        run: |
          source assume_role pp
          export AUTHORIZATION_CODE="$(aws secretsmanager get-secret-value --secret-id devops/performance_testing_token --query SecretString --output text)"
          source assume_role -u
          artillery run \
            --config "config_${{ inputs.env }}.yml" \
            --overrides '{
              "config":{
                "phases":[
                  {
                    "duration":${{ inputs.duration }},
                    "arrivalRate":${{ inputs.arrival_rate }},
                    "name":"${{ inputs.arrival_rate }}rps"
                  }
                ]
              }
          }' \
          tests/performance/${{ inputs.test_file }} \
          | tee out.txt \
          || true
      - name: Get job id
        run: |
          jid=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}/jobs | jq .jobs[-1].id)
          url=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}/actions/jobs/$jid | jq .html_url)
          echo "URL=$url" >> $GITHUB_ENV
      - name: Post to Slack
        run: |
          awk '/All VUs finished/,0' out.txt | ppslack -f "${{ github.actor }}" -t "performance-testing" -Hs "[${{ inputs.env }}] Performance Test: ${{ inputs.test_file }} Duration: ${{ inputs.duration }} RPS: ${{ inputs.arrival_rate }} (<${{ env.PIPELINE }}|Pipeline>, <${{ env.URL }}|Job>)" || true
